config/routes.rb
Rails.application.routes.draw do
  resources :pets

  resources :foundations

  resources :users

   root 'home#index'

end

app/models/foundation.rb
class Foundation < ActiveRecord::Base
end

app/models/pet.rb
class Pet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foundations_controller.rb
class FoundationsController < ApplicationController
  before_action :set_foundation, only: [:show, :edit, :update, :destroy]

  # GET /foundations
  # GET /foundations.json
  def index
    @foundations = Foundation.all
  end

  # GET /foundations/1
  # GET /foundations/1.json
  def show
  end

  # GET /foundations/new
  def new
    @foundation = Foundation.new
  end

  # GET /foundations/1/edit
  def edit
  end

  # POST /foundations
  # POST /foundations.json
  def create
    @foundation = Foundation.new(foundation_params)

    respond_to do |format|
      if @foundation.save
        format.html { redirect_to @foundation, notice: 'Foundation was successfully created.' }
        format.json { render :show, status: :created, location: @foundation }
      else
        format.html { render :new }
        format.json { render json: @foundation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foundations/1
  # PATCH/PUT /foundations/1.json
  def update
    respond_to do |format|
      if @foundation.update(foundation_params)
        format.html { redirect_to @foundation, notice: 'Foundation was successfully updated.' }
        format.json { render :show, status: :ok, location: @foundation }
      else
        format.html { render :edit }
        format.json { render json: @foundation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foundations/1
  # DELETE /foundations/1.json
  def destroy
    @foundation.destroy
    respond_to do |format|
      format.html { redirect_to foundations_url, notice: 'Foundation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foundation
      @foundation = Foundation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foundation_params
      params.require(:foundation).permit(:foundation_name, :username, :email, :password, :location, :website)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
   	end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:pet_name, :pet_age, :pet_type, :pet_breed, :pet_gender, :pet_size, :pet_special_needs, :pet_household_match)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fist_name, :last_name, :email, :password, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foundations_helper.rb
module FoundationsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foundations/_form.html.erb
<%= form_for(@foundation) do |f| %>
  <% if @foundation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foundation.errors.count, "error") %> prohibited this foundation from being saved:</h2>

      <ul>
      <% @foundation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foundation_name %><br>
    <%= f.text_field :foundation_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foundations/edit.html.erb
<h1>Editing Foundation</h1>

<%= render 'form' %>

<%= link_to 'Show', @foundation %> |
<%= link_to 'Back', foundations_path %>

app/views/foundations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foundations</h1>

<table>
  <thead>
    <tr>
      <th>Foundation name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Location</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foundations.each do |foundation| %>
      <tr>
        <td><%= foundation.foundation_name %></td>
        <td><%= foundation.username %></td>
        <td><%= foundation.email %></td>
        <td><%= foundation.password %></td>
        <td><%= foundation.location %></td>
        <td><%= foundation.website %></td>
        <td><%= link_to 'Show', foundation %></td>
        <td><%= link_to 'Edit', edit_foundation_path(foundation) %></td>
        <td><%= link_to 'Destroy', foundation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foundation', new_foundation_path %>

app/views/foundations/new.html.erb
<h1>New Foundation</h1>

<%= render 'form' %>

<%= link_to 'Back', foundations_path %>

app/views/foundations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foundation name:</strong>
  <%= @foundation.foundation_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @foundation.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @foundation.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @foundation.password %>
</p>

<p>
  <strong>Location:</strong>
  <%= @foundation.location %>
</p>

<p>
  <strong>Website:</strong>
  <%= @foundation.website %>
</p>

<%= link_to 'Edit', edit_foundation_path(@foundation) %> |
<%= link_to 'Back', foundations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 7]>                  <html class="ie7 no-js" lang="en">     <![endif]-->
<!--[if lte IE 8]>              <html class="ie8 no-js" lang="en">     <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="not-ie no-js" lang="en">  <!--<![endif]-->
<head>
<!-- STYLESHEETS -->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>


	<!-- Basic Page Needs
	================================================== -->
	<meta charset="utf-8">
	<title>Adopta-me</title>
	<meta name="description" content="Adopta-me es una base de datos en línea que permite la búsqueda de mascotas sin hogar elementonibles para adopción en Colombia.">
	<meta name="author" content="Adopta-me">


	<!-- Mobile Specific Metas (RESPONSIVE!!!!!)
	================================================== -->
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
	
	<!-- Google Web Fonts
	================================================== -->
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic|Bitter:700' rel='stylesheet' type='text/css'>
	
	<!-- CSS
	================================================== -->
   <!-- Base + Vendors CSS -->
   <!-- 	<link rel="stylesheet" href="css/bootstrap.min.css">
   	<link rel="stylesheet" href="css/fonts/font-awesome/css/font-awesome.css">
   	<link rel="stylesheet" href="css/fonts/entypo/css/entypo.css">
   	<link rel="stylesheet" href="vendor/owl-carousel/owl.carousel.css" media="screen">
	<link rel="stylesheet" href="vendor/owl-carousel/owl.theme.css" media="screen">
	<link rel="stylesheet" href="vendor/magnific-popup/magnific-popup.css" media="screen">
	<link rel="stylesheet" href="vendor/flexslider/flexslider.css" media="screen">

   <!-- Theme CSS-->
	<!-- <link rel="stylesheet" href="css/theme.css">
	<link rel="stylesheet" href="css/theme-elements.css">
   	<link rel="stylesheet" href="css/animate.min.css"> --> 

   

   <!-- Head Libs -->
	<!--  <script src="vendor/modernizr.js"></script> -->

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<script src="vendor/respond.min.js"></script>
	<![endif]-->

	<!--[if IE]>
		<link rel="stylesheet" href="css/ie.css">
	<![endif]-->
	
	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="144x144" href="images/apple-touch-icon-144x144.png">
	
</head>
<body>

	<div class="site-wrapper">

<!-- Header -->
		<header class="header header-menu-fullw">

			<div class="header-top">
				<div class="container">
					<div class="header-top-left">
						<ul class="header-top-nav">
							<span class="register">
							<a href="#" class="btn btn-sm btn-warning">Registrate aquí</a>
						</span>
						</ul>
					</div>
					<div class="header-top-right">
						<span class="register">
							¿Ya tienes una cuenta? <a href="#" class="btn btn-sm btn-warning">Inicia Sesión</a>
						</span>
					</div>
				</div>
			</div>
			<div class="header-main">
				<div class="container">
<!-- Logo -->
					<div class="logo">
						<!-- "/" return to root on click -->
						<a href="/"><%= image_tag("logo-adoptame-alpha200.png")%></a>
						<!-- <h1><a href="index.html"><span>Pet</span>Sitter</a></h1>
						<p class="tagline">Find an Awesome PetSitter</p> -->
					</div>
<!-- Logo / End -->

					<button type="button" class="navbar-toggle">
			        <i class="fa fa-bars"></i>
			      </button>

 <!-- Banner -->
			      <div class="head-info">
			      	<ul class="head-info-list">
			      		<!-- <li><span>Contactenos:</span> +1 (234) 567890</li> -->
			      		<li><span>Email de contacto:</span> <a href="mailto:info@adoptame.co">info@adoptame.co</a></li>
			      	</ul>
			      	<ul class="social-links">
			      		<li><a href="https://twitter.com/Adoptame_co"><i class="fa fa-twitter"></i></a></li>
							<li><a href="https://www.facebook.com/pages/Adopta-Me/319083928262527"><i class="fa fa-facebook"></i></a></li>
							<!-- <li><a href="#"><i class="fa fa-google-plus"></i></a></li> -->
							<!-- <li><a href="#"><i class="fa fa-pinterest"></i></a></li> -->
							<li><a href="http://instagram.com/adopota_me"><i class="fa fa-instagram"></i></a></li>
							<!-- <li><a href="#"><i class="fa fa-rss"></i></a></li> -->
						</ul>
			      </div>
<!-- Banner / End -->
				</div>
			</div>
			
<!-- Navigation -->
			<nav class="nav-main">
				<div class="container">
					<ul data-breakpoint="992" class="flexnav">

<!-- Nav Bar Options Link: Home  -->						
						<li class="active"><a href="index.html">Inicio</a></li>
<!-- Nav Bar Options Link: Pages  -->
							<li><a href="#">Pages</a>
								<ul>
									<li><a href="page-about.html">About Us</a></li>
									<li><a href="page-services.html">Services</a></li>
									<li><a href="page-team.html">Team</a></li>
									<li><a href="page-team-member.html">Team Member</a></li>
									<li><a href="page-faqs.html">FAQs</a></li>
									<li><a href="page-fullwidth.html">Full Width</a></li>
									<li><a href="page-left-sidebar.html">Left Sidebar</a></li>
									<li><a href="page-right-sidebar.html">Right Sidebar</a></li>
									<li><a href="page-404.html">404</a></li>
									<li><a href="page-coming-soon.html">Coming Soon</a></li>
								</ul>
							<li>
<!-- Nav Bar Options Link: Foundations  -->						
						<li><a href="#">Fundaciones</a>
							<ul>
								<li><a href="features-shortcodes.html">Shortcodes</a></li>
								<li><a href="features-pricing-tables.html">Pricing Tables</a></li>
								<li><a href="features-typography.html">Typography</a></li>
								<li><a href="features-columns.html">Columns</a></li>
								<li><a href="features-icons.html">Icons</a></li>
							</ul>
						</li>

<!-- Nav Bar Options Link: Contacts  -->						
						<li><a href="contacts.html">Contacts</a></li>
					</ul>
				</div>
			</nav>
<!-- Navigation / End -->

<!-- Nav Bar Options Link: Services  -->						
						<!-- <li><a href="#">Pet Sitters</a>
							<ul>
								<li><a href="job-post-profile.html">Post a Profile</a></li>
								<li><a href="job-post-job.html">Post a Job</a></li>
								<li><a href="job-list.html">Pet Sitters List</a></li>
								<li><a href="job-dashboard.html">Dashboard</a></li>
								<li><a href="job-profile.html">Profile</a></li>
							</ul>
						</li> -->

<!-- Nav Bar Options Link: Portfolio  -->						
						<!-- <li><a href="portfolio-3cols.html">Portfolio</a>
							<ul>
								<li><a href="portfolio-2cols.html">Portfolio 2 cols</a></li>
								<li><a href="portfolio-3cols.html">Portfolio 3 cols</a></li>
								<li><a href="portfolio-4cols.html">Portfolio 4 cols</a></li>
								<li><a href="portfolio-fullw.html">Portfolio Full Width</a></li>
								<li><a href="portfolio-single-halfwidth.html">Single Half Width</a></li>
								<li><a href="portfolio-single-fullwidth.html">Single Full Width</a></li>
							</ul>
						</li> -->

<!-- Nav Bar Options Link: Blog  -->						
						<!-- <li><a href="blog-right-sidebar.html">Blog</a>
							<ul>
								<li><a href="blog-right-sidebar.html">Blog Right Sidebar</a></li>
								<li><a href="blog-left-sidebar.html">Blog Left Sidebar</a></li>
								<li><a href="blog-fullwidth.html">Blog Full Width</a></li>
								<li><a href="blog-post.html">Single Post</a></li>
							</ul>
						</li> -->


			
		</header>



	<%= yield %>

<!-- Footer -->
			<footer class="footer" id="footer">
				<div class="footer-widgets">
					<div class="container">
						<div class="row">
							<div class="col-sm-6 col-md-2">
<!-- Widget :: Custom Menu -->
								<div class="widget_nav_menu widget widget__footer">
									<h3 class="widget-title">Información</h3>
									<div class="widget-content">
										<ul>
											<!-- <li><a href="#">FAQ’s</a></li>
											<li><a href="#">Press</a></li>
											<li><a href="#"></a></li> -->
											<li><a href="#">Sobre Nosotros</a></li>
											<li><a href="#">Preguntas Frecuentes</a></li>
											<li><a href="#">Contáctenos</a></li>
										</ul>
									</div>
								</div>
<!-- /Widget :: Custom Menu -->
							</div>
							<div class="col-sm-6 col-md-2">
<!-- Widget :: Categories -->
								<div class="widget_categories widget widget__footer">
									<h3 class="widget-title">Servicios</h3>
									<div class="widget-content">
										<ul>
											<li><a href="#">Adopciones</a></li>
											<li><a href="#">Apadrinamientos</a></li>
											<li><a href="#">Donaciones</a></li>
											<li><a href="#">Voluntarios</a></li>
											<!-- <li><a href="#">Pet Care Costs</a></li> -->
										</ul>
									</div>
								</div>
<!-- /Widget :: Categories -->
							</div>

							<div class="clearfix visible-sm"></div>

							<div class="col-sm-6 col-md-4">
<!-- Widget :: Latest Posts -->
								<div class="latest-posts-widget widget widget__footer">
									<!-- <h3 class="widget-title"></h3> -->
									<div class="widget-content">
<!-- Api Twitter Widget Last Tweets -->
										<a class="twitter-timeline"  href="https://twitter.com/Adoptame_co" data-widget-id="510916307567378432">Tweets por @Adoptame_co</a>
            							<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<!-- End Api Twitter Widget Last Tweets -->        
									</div>
								</div>
<!-- /Widget :: Latest Posts -->
							</div>
							<div class="col-sm-6 col-md-4">
								<!-- Widget :: Newsletter -->
								<div class="widget_newsletter widget widget__footer">
									<h3 class="widget-title">Suscribete </h3>
									<div class="widget-content">
										<p>¿Quieres estar al tanto de nuestras últimas noticias y actualizaciones? Suscribete ahora!</p>

										<form action="#" method="POST" role="form">
											<div class="row">
												<div class="col-md-8">
													<div class="form-group">
														<input type="email" class="form-control" placeholder="Enter your email here...">
													</div>
												</div>
												<div class="col-md-4">
													<button type="submit" class="btn btn-success btn-block">Subscribe</button>
												</div>
											</div>
										</form>
									</div>
								</div>
<!-- /Widget :: Newsletter -->
							</div>
						</div>
					</div>
				</div>
				<div class="footer-copyright">
					<div class="container">
						<div class="row">
							<div class="col-sm-6 col-md-4">
								Copyright &copy; 2014  <a href="index.html">Adopta-me</a> &nbsp;| &nbsp;All Rights Reserved
							</div>
							<div class="col-sm-6 col-md-8">
								<div class="social-links-wrapper">
									<span class="social-links-txt">Keep in Touch</span>
									<ul class="social-links social-links__light">
										<li><a href="https://twitter.com/Adoptame_co"><i class="fa fa-twitter"></i></a></li>
										<li><a href="https://www.facebook.com/pages/Adopta-Me/319083928262527"><i class="fa fa-facebook"></i></a></li>
										<!-- <li><a href="#"><i class="fa fa-google-plus"></i></a></li> -->
										<!-- <li><a href="#"><i class="fa fa-pinterest"></i></a></li> -->
										<li><a href="http://instagram.com/adopota_me"><i class="fa fa-instagram"></i></a></li>
										<!-- <li><a href="#"><i class="fa fa-rss"></i></a></li> -->
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</footer>
<!-- Footer / End -->

<script>
		jQuery(function($){
			$('body').addClass('loading');
		});
		
		$(window).load(function(){
			$('.flexslider').flexslider({
				animation: "fade",
				controlNav: true,
				directionNav: false,
				prevText: "",
				nextText: "",
				start: function(slider){
					$('body').removeClass('loading');
				}
			});
		});
	</script>


<!-- Google Analytics Information -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54773894-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Pet name</th>
      <th>Pet age</th>
      <th>Pet type</th>
      <th>Pet breed</th>
      <th>Pet gender</th>
      <th>Pet size</th>
      <th>Pet special needs</th>
      <th>Pet household match</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.pet_name %></td>
        <td><%= pet.pet_age %></td>
        <td><%= pet.pet_type %></td>
        <td><%= pet.pet_breed %></td>
        <td><%= pet.pet_gender %></td>
        <td><%= pet.pet_size %></td>
        <td><%= pet.pet_special_needs %></td>
        <td><%= pet.pet_household_match %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet name:</strong>
  <%= @pet.pet_name %>
</p>

<p>
  <strong>Pet age:</strong>
  <%= @pet.pet_age %>
</p>

<p>
  <strong>Pet type:</strong>
  <%= @pet.pet_type %>
</p>

<p>
  <strong>Pet breed:</strong>
  <%= @pet.pet_breed %>
</p>

<p>
  <strong>Pet gender:</strong>
  <%= @pet.pet_gender %>
</p>

<p>
  <strong>Pet size:</strong>
  <%= @pet.pet_size %>
</p>

<p>
  <strong>Pet special needs:</strong>
  <%= @pet.pet_special_needs %>
</p>

<p>
  <strong>Pet household match:</strong>
  <%= @pet.pet_household_match %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Fist name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fist_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fist name:</strong>
  <%= @user.fist_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>